Import('env')
# Import('utils_lib')
Import('utils_lib_static')

test_env = env.Clone()

test_env.Append(CCFLAGS = Split('-fpermissive -Wint-to-pointer-cast'))
# test_env.Append(CCFLAGS = Split('-Wall -g -lgtest -lgtest_main -lpthread -lgenesis_utils'),
#                 CPPPATH = ['#utils', '#src'],
#                 LIBPATH = ['utils', 'src'])
## LIBS = ['genesis_utils', 'gtest_main', 'pthread', 'gtest']
#print test_env['LIBPATH']
#print test_env['CPPPATH']
#print test_env['LIBS']

test_env.Program('test_allocator', ['test_allocator.cpp'], LIBS=[utils_lib_static, 'gtest', 'gtest_main', 'pthread'],
                 CPPPATH = ['#utils', '#src'])

test_env.Program('test_dlist', ['test_dlist.cpp'], LIBS=[utils_lib_static, 'gtest', 'gtest_main', 'pthread'],
                 CPPPATH = ['#utils', '#src'])

test_env.Program('test_darray', ['test_darray.cpp'], LIBS=[utils_lib_static, 'gtest', 'gtest_main', 'pthread'],
                 CPPPATH = ['#utils', '#src'])
