Import('env')
Import('utils_lib_static')
Import('genesis_lib_static')

select_loop_lib_src = ['main_loop_select.c', 'module_select_loop.c']

select_loop_lib_env = env.Clone()
select_loop_lib_shared = select_loop_lib_env.SharedLibrary('select_loop',
                                                           select_loop_lib_src,
                                                           LIBS = [utils_lib_static],
                                                           CPPPATH = ['#utils', '#src/core'])


select_loop_lib_static = select_loop_lib_env.StaticLibrary('select_loop',
                                                           select_loop_lib_src,
                                                           LIBS = [utils_lib_static, genesis_lib_static],
                                                           CPPPATH = ['#utils', '#src/core'])

Export('select_loop_lib_shared')
Export('select_loop_lib_static')

