#env = Environment()
Import('env')

utils_env = env.Clone()
env_flags = utils_env.ParseFlags("-Wall -g -pthread -DDLIST_TEST")
utils_env.MergeFlags(env_flags)

dlist_src = ['dlist.c', 'locker_nest.c', 'locker_pthread.c']

utils_env.Program('dlist_test', dlist_src)

