Import('env')
Import('utils_lib_static')

genesis_lib_src = ['pipe_default.c', 'source_timer.c', 'source_primary.c']

genesis_lib_env = env.Clone()
genesis_lib_shared = genesis_lib_env.SharedLibrary('genesis', genesis_lib_src, LIBS =
                                                   [utils_lib_static], CPPPATH = ['#utils'])

genesis_lib_static = genesis_lib_env.StaticLibrary('genesis', genesis_lib_src, LIBS =
                                                   [utils_lib_static], CPPPATH = ['#utils'])

Export('genesis_lib_shared')
Export('genesis_lib_static')

genesis_lib = genesis_lib_shared

Return('genesis_lib')
